version: "3"
services:
  postgres:
    image: "postgres:10"
    environment:
    - POSTGRES_PASSWORD=Password1!
    ports:
    - 5432:5432
  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbit"
    ports:
    - 5672:5672
    - 15672:15672
  backend:
    image: "workout-diary-backend"
    ports:
    - 8080:8080
    depends_on:
    - postgres
    - rabbitmq
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    - SPRING_RABBITMQ_HOST=rabbitmq